// Generic built-in device templates (no vendor artwork). The default stick and throttle are original holographic wireframe drawings
// generated by scripts/gen-default-stick.mjs (1000 x 900) and scripts/gen-default-throttle.mjs (1000 x 800); the classic ones and the
// gamepad are simple SVG drawn here (canvas 1000 x 625).
import type { Callout, CalloutKind, DeviceTemplate } from './templates';
import { DEFAULT_STICK_ANCHORS, DEFAULT_STICK_H, DEFAULT_STICK_REGIONS, DEFAULT_STICK_SVG, DEFAULT_STICK_W } from './defaultStickArt';
import { DEFAULT_THROTTLE_ANCHORS, DEFAULT_THROTTLE_H, DEFAULT_THROTTLE_INPUT_REGIONS, DEFAULT_THROTTLE_REGIONS, DEFAULT_THROTTLE_SVG, DEFAULT_THROTTLE_W } from './defaultThrottleArt';

const W = 1000, H = 625;
const svgUrl = (body: string) =>
  `data:image/svg+xml;utf8,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" fill="none" stroke="#7fa6c2" stroke-width="3" stroke-linejoin="round">${body}</svg>`)}`;
const fill = 'fill="#0f2235"';
const cross = (x: number, y: number, r: number) =>
  `<circle cx="${x}" cy="${y}" r="${r}" ${fill}/><path d="M${x} ${y - r + 5}v${2 * r - 10}M${x - r + 5} ${y}h${2 * r - 10}" stroke-width="2"/>`;
const btn = (x: number, y: number, r = 11) => `<circle cx="${x}" cy="${y}" r="${r}" ${fill}/>`;

/** callout from pixel coordinates on the 1000 x 625 canvas */
const c = (id: string, kind: CalloutKind, inputs: string[], ax: number, ay: number, bx: number, by: number, label?: string, group?: string): Callout => ({
  id, kind, inputs, anchor: { x: ax / W, y: ay / H }, box: { x: bx, y: by }, ...(label ? { label } : {}), ...(group ? { group } : {}),
});
const hat = (n: number) => ['up', 'right', 'down', 'left'].map((d) => `hat${n}_${d}`);

/* ------------------------------------------------ default stick: anchors and glow regions come from the generated art */
const DW = DEFAULT_STICK_W, DH = DEFAULT_STICK_H;
/** callout on the default stick: `art` names the control in the drawing; box = label centre (fractions) */
const d = (id: string, art: string, kind: CalloutKind, inputs: string[], bx: number, by: number, label?: string, group?: string): Callout => {
  const [ax, ay] = DEFAULT_STICK_ANCHORS[art];
  const region = DEFAULT_STICK_REGIONS[art];
  return { id, kind, inputs, anchor: { x: ax / DW, y: ay / DH }, box: { x: bx, y: by }, ...(label ? { label } : {}), ...(group ? { group } : {}), ...(region ? { region } : {}) };
};
/** callout on the default throttle art (same idea as `d`) */
const TW = DEFAULT_THROTTLE_W, TH = DEFAULT_THROTTLE_H;
const t = (id: string, art: string, kind: CalloutKind, inputs: string[], bx: number, by: number, label?: string, group?: string): Callout => {
  const [ax, ay] = DEFAULT_THROTTLE_ANCHORS[art];
  const region = DEFAULT_THROTTLE_REGIONS[art], inputRegions = DEFAULT_THROTTLE_INPUT_REGIONS[art];
  return { id, kind, inputs, anchor: { x: ax / TW, y: ay / TH }, box: { x: bx, y: by }, ...(label ? { label } : {}), ...(group ? { group } : {}), ...(region ? { region } : {}), ...(inputRegions ? { inputRegions } : {}) };
};
const b = (...n: number[]) => n.map((i) => `button${i}`);
const DEFAULT_THROTTLE: DeviceTemplate = {
  version: 1, id: 'builtin-throttle', name: 'Generic throttle', builtin: true, slot: 'js',
  image: `data:image/svg+xml;utf8,${encodeURIComponent(DEFAULT_THROTTLE_SVG)}`, aspect: TW / TH, match: [],
  callouts: [
    // left column: left grip, left lever, panel (pilot side); ordered so that leader lines do not cross
    t('hat3', 'hat3', 'hat', [...hat(3), 'button10'], 0.125, 0.055, undefined, 'Left grip'),
    t('trgL', 'trgL', 'button', b(4), 0.115, 0.19, 'Left trigger', 'Left grip'),
    t('lz', 'lz', 'axis', ['z'], 0.115, 0.3, 'Left lever', 'Axes'),
    t('sld', 'sld', 'axis', ['slider2'], 0.115, 0.385, 'Slider', 'Axes'),
    t('mode', 'mode', 'switch', b(24, 25, 26, 27, 28), 0.115, 0.48, 'Mode 1 – 5', 'Panel'),
    t('keys', 'keys', 'buttons', b(11, 12, 13, 14, 15, 16), 0.115, 0.585, 'Keypad (lit)', 'Panel'),
    t('e1', 'e1', 'encoder', b(18, 19, 20), 0.115, 0.7, 'Encoder E1', 'Panel'),
    t('red', 'red', 'button', b(17), 0.115, 0.8, 'Emergency (guarded)', 'Panel'),
    // right column: right grip, right lever, flaps
    t('whl', 'whl', 'encoder', b(6, 7), 0.885, 0.055, 'Thumb wheel', 'Right grip'),
    t('hat1', 'hat1', 'hat', [...hat(1), 'button8'], 0.875, 0.165, undefined, 'Right grip'),
    t('ms', 'ms', 'axis', ['x', 'y'], 0.885, 0.3, 'Mini-stick', 'Right grip'),
    t('msb', 'ms', 'button', b(5), 0.885, 0.38, 'Mini-stick press', 'Right grip'),
    t('hat2', 'hat2', 'hat', [...hat(2), 'button9'], 0.875, 0.49, undefined, 'Right grip'),
    t('trgR', 'trgR', 'switch', b(1, 2), 0.885, 0.605, 'Trigger (2-stage)', 'Right grip'),
    t('gb1', 'gb1', 'button', b(3), 0.885, 0.685, 'Thumb button', 'Right grip'),
    t('lrz', 'lrz', 'axis', ['rotz'], 0.885, 0.76, 'Right lever', 'Axes'),
    t('flaps', 'flaps', 'axis', ['slider1'], 0.885, 0.835, 'Flaps lever', 'Axes'),
    t('e2', 'e2', 'encoder', b(21, 22, 23), 0.885, 0.91, 'Encoder E2', 'Panel'),
    // bottom row: toggles T1 – T3
    t('t1', 't1', 'switch', b(29, 30), 0.3, 0.915, 'Toggle T1 (on-off-on)', 'Panel'),
    t('t2', 't2', 'button', b(31), 0.5, 0.915, 'Toggle T2', 'Panel'),
    t('t3', 't3', 'button', b(32), 0.66, 0.915, 'Toggle T3', 'Panel'),
  ],
};

const DEFAULT_STICK: DeviceTemplate = {
  version: 1, id: 'builtin-stick', name: 'Generic stick', builtin: true, slot: 'js',
  image: `data:image/svg+xml;utf8,${encodeURIComponent(DEFAULT_STICK_SVG)}`, aspect: DW / DH, match: [],
  callouts: [
    // left column, top to bottom (grip front / thumb side)
    d('hat1', 'hat1', 'hat', [...hat(1), 'button12'], 0.125, 0.06, undefined, 'Grip head'),
    d('enc', 'enc', 'encoder', ['button10', 'button11'], 0.115, 0.14, 'Thumb wheel', 'Grip head'),
    d('hat3', 'hat3', 'hat', [...hat(3), 'button14'], 0.125, 0.22, undefined, 'Grip head'),
    d('b8', 'b8', 'button', ['button8'], 0.115, 0.3, 'Index button', 'Grip head'),
    d('b6', 'b6', 'button', ['button6'], 0.115, 0.375, 'Thumb button (front)', 'Grip head'),
    d('hat4', 'hat4', 'hat', [...hat(4), 'button15'], 0.125, 0.45, undefined, 'Grip head'),
    d('trig', 'trig', 'switch', ['button1', 'button2'], 0.115, 0.55, 'Trigger (2-stage)', 'Grip'),
    d('b4', 'b4', 'button', ['button4'], 0.115, 0.66, 'Pinky paddle', 'Grip'),
    d('b5', 'b5', 'button', ['button5'], 0.115, 0.75, 'Pinky button', 'Grip'),
    d('rz', 'rz', 'axis', ['rotz'], 0.115, 0.825, 'Twist', 'Axes'),
    d('rowL', 'rowL', 'buttons', ['button16', 'button17', 'button18', 'button19'], 0.125, 0.915, 'Deck buttons (left)', 'Base'),
    // right column, top to bottom (top panel, base deck)
    d('ms', 'ms', 'axis', ['rotx', 'roty'], 0.885, 0.07, 'Mini-stick', 'Grip head'),
    d('msb', 'ms', 'button', ['button9'], 0.885, 0.175, 'Mini-stick press', 'Grip head'),
    d('b3', 'b3', 'button', ['button3'], 0.885, 0.255, 'Weapon release', 'Grip head'),
    d('hat2', 'hat2', 'hat', [...hat(2), 'button13'], 0.875, 0.345, undefined, 'Grip head'),
    d('b7', 'b7', 'button', ['button7'], 0.885, 0.44, 'Thumb button (rear)', 'Grip head'),
    d('rowR', 'rowR', 'buttons', ['button20', 'button21', 'button22', 'button23'], 0.875, 0.53, 'Deck buttons (right)', 'Base'),
    d('tog2', 'tog2', 'switch', ['button26', 'button27'], 0.885, 0.615, 'Toggle (right)', 'Base'),
    d('xy', 'xy', 'axis', ['x', 'y'], 0.885, 0.715, 'Stick X / Y', 'Axes'),
    d('fkeys', 'fkeys', 'buttons', ['button28', 'button29', 'button30'], 0.875, 0.825, 'F1 – F3', 'Base'),
    d('tog1', 'tog1', 'switch', ['button24', 'button25'], 0.885, 0.915, 'Toggle (left)', 'Base'),
    // bottom row: the three thumbwheels on the sloped pilot panel
    d('whl1', 'whl1', 'axis', ['slider1'], 0.33, 0.955, 'Lever wheel', 'Base'),
    d('whl2', 'whl2', 'axis', ['slider2'], 0.5, 0.955, 'Centre wheel', 'Base'),
    d('whl3', 'whl3', 'encoder', ['button31', 'button32'], 0.67, 0.955, 'Encoder EN1', 'Base'),
  ],
};

const STICK = svgUrl([
  '<rect x="370" y="520" width="260" height="80" rx="18" fill="#0b1a2a"/>',
  '<rect x="484" y="395" width="32" height="128" rx="6" fill="#0b1a2a"/>',
  '<path d="M432 405 Q418 300 428 210 Q436 120 470 96 Q520 74 560 100 Q590 124 580 220 Q574 320 568 405 Z" fill="#0b1a2a"/>',
  '<path d="M424 222 q-22 6 -18 36 q4 22 22 20" fill="#0f2235"/>',
  cross(470, 150, 22), cross(530, 185, 16), btn(556, 124, 10), btn(520, 228), btn(546, 272), btn(442, 330, 9),
  btn(420, 560), btn(580, 560), '<rect x="596" y="574" width="26" height="14" rx="4" fill="#0f2235"/>',
  '<path d="M455 470 h-30 m0 0 l10 -8 m-10 8 l10 8 M545 470 h30 m0 0 l-10 -8 m10 8 l-10 8" stroke-width="2"/>',
  '<path d="M560 330 q24 -20 10 -50" stroke-width="2"/><path d="M570 280 l-10 2 m10 -2 l2 10" stroke-width="2"/>',
].join(''));

const THROTTLE = svgUrl([
  '<rect x="290" y="470" width="420" height="130" rx="20" fill="#0b1a2a"/>',
  '<path d="M486 470 L470 290 L530 290 L540 470 Z" fill="#0b1a2a"/>',
  '<rect x="370" y="130" width="250" height="160" rx="40" fill="#0b1a2a"/>',
  cross(430, 170, 20), cross(510, 155, 18), '<circle cx="578" cy="196" r="17" fill="#0f2235"/><circle cx="578" cy="196" r="6"/>',
  btn(455, 228), btn(395, 250, 10), '<rect x="526" y="236" width="34" height="18" rx="9" fill="#0f2235"/>',
  '<rect x="630" y="492" width="20" height="60" rx="6" fill="#0f2235"/>', '<rect x="636" y="500" width="8" height="18" rx="3" fill="#7fa6c2"/>',
  '<rect x="350" y="530" width="20" height="34" rx="5" fill="#0f2235"/>', '<path d="M360 530 v-14" stroke-width="5"/>', btn(560, 545, 12),
  '<path d="M505 330 v60 m0 -60 l-8 10 m8 -10 l8 10 m-8 50 l-8 -10 m8 10 l8 -10" stroke-width="2"/>',
].join(''));

const GAMEPAD = svgUrl([
  '<path d="M300 205 Q500 170 700 205 Q790 220 815 330 Q840 470 770 500 Q720 515 680 450 L640 410 L360 410 L320 450 Q280 515 230 500 Q160 470 185 330 Q210 220 300 205 Z" fill="#0b1a2a"/>',
  '<rect x="262" y="150" width="76" height="28" rx="12" fill="#0f2235"/><rect x="662" y="150" width="76" height="28" rx="12" fill="#0f2235"/>',
  '<rect x="258" y="190" width="84" height="18" rx="8" fill="#0f2235"/><rect x="658" y="190" width="84" height="18" rx="8" fill="#0f2235"/>',
  '<circle cx="310" cy="285" r="34" fill="#0f2235"/><circle cx="310" cy="285" r="20"/>',
  '<circle cx="610" cy="380" r="34" fill="#0f2235"/><circle cx="610" cy="380" r="20"/>',
  '<path d="M378 352 h24 v24 h24 v24 h-24 v24 h-24 v-24 h-24 v-24 h24 z" fill="#0f2235"/>',
  btn(690, 245, 15), btn(730, 285, 15), btn(690, 325, 15), btn(650, 285, 15),
  '<rect x="440" y="275" width="30" height="16" rx="8" fill="#0f2235"/><rect x="530" y="275" width="30" height="16" rx="8" fill="#0f2235"/>',
].join(''));

export const BUILTIN_TEMPLATES: DeviceTemplate[] = [
  DEFAULT_STICK,
  DEFAULT_THROTTLE,
  {
    version: 1, id: 'builtin-stick-classic', name: 'Generic stick (classic)', builtin: true, slot: 'js', image: STICK, aspect: W / H, match: [],
    callouts: [
      c('hat1', 'hat', hat(1), 470, 150, 0.13, 0.1, undefined, 'Grip'),
      c('b2', 'button', ['button2'], 556, 124, 0.86, 0.1, undefined, 'Grip'),
      c('hat2', 'hat', hat(2), 530, 185, 0.86, 0.25, undefined, 'Grip'),
      c('b1', 'button', ['button1'], 412, 246, 0.13, 0.3, 'Trigger', 'Grip'),
      c('b3', 'button', ['button3'], 520, 228, 0.86, 0.39, undefined, 'Grip'),
      c('b4', 'button', ['button4'], 546, 272, 0.86, 0.5, undefined, 'Grip'),
      c('b5', 'button', ['button5'], 442, 330, 0.13, 0.48, 'Pinky', 'Grip'),
      c('xy', 'axis', ['x', 'y'], 500, 470, 0.13, 0.66, 'Stick X / Y', 'Axes'),
      c('rz', 'axis', ['rotz'], 568, 300, 0.86, 0.62, 'Twist', 'Axes'),
      c('b6', 'button', ['button6'], 420, 560, 0.13, 0.84, undefined, 'Base'),
      c('b7', 'button', ['button7'], 580, 560, 0.86, 0.76, undefined, 'Base'),
      c('s1', 'axis', ['slider1'], 609, 581, 0.86, 0.9, 'Base slider', 'Axes'),
    ],
  },
  {
    version: 1, id: 'builtin-throttle-classic', name: 'Generic throttle (classic)', builtin: true, slot: 'js', image: THROTTLE, aspect: W / H, match: [],
    callouts: [
      c('hat1', 'hat', hat(1), 430, 170, 0.13, 0.1, undefined, 'Handle'),
      c('hat2', 'hat', hat(2), 510, 155, 0.86, 0.1, undefined, 'Handle'),
      c('ms', 'axis', ['rotx', 'roty'], 578, 196, 0.86, 0.26, 'Mini-stick', 'Handle'),
      c('b1', 'button', ['button1'], 455, 228, 0.13, 0.28, undefined, 'Handle'),
      c('b4', 'button', ['button4'], 395, 250, 0.13, 0.42, undefined, 'Handle'),
      c('enc', 'encoder', ['button2', 'button3'], 543, 245, 0.86, 0.42, 'Encoder', 'Handle'),
      c('z', 'axis', ['z'], 505, 360, 0.13, 0.6, 'Throttle', 'Axes'),
      c('s1', 'axis', ['slider1'], 640, 510, 0.86, 0.6, 'Base slider', 'Axes'),
      c('sw', 'switch', ['button5', 'button6', 'button7'], 360, 540, 0.13, 0.82, '3-way switch', 'Base'),
      c('b8', 'button', ['button8'], 560, 545, 0.86, 0.8, undefined, 'Base'),
    ],
  },
  {
    version: 1, id: 'builtin-gamepad', name: 'Gamepad', builtin: true, slot: 'gp', image: GAMEPAD, aspect: W / H, match: [],
    callouts: [
      c('lt', 'button', ['triggerl_btn'], 300, 162, 0.1, 0.08, 'LT', 'Left'),
      c('lb', 'button', ['shoulderl'], 300, 199, 0.1, 0.2, 'LB', 'Left'),
      c('ls', 'axis', ['thumblx', 'thumbly'], 300, 280, 0.1, 0.33, 'Left stick', 'Left'),
      c('l3', 'button', ['thumbl'], 318, 292, 0.1, 0.46, 'L3 (press)', 'Left'),
      c('dpad', 'hat', ['dpad_up', 'dpad_right', 'dpad_down', 'dpad_left'], 390, 388, 0.1, 0.63, 'D-pad', 'Left'),
      c('back', 'button', ['back'], 455, 283, 0.32, 0.92, 'Back / View'),
      c('start', 'button', ['start'], 545, 283, 0.66, 0.92, 'Start / Menu'),
      c('rt', 'button', ['triggerr_btn'], 700, 162, 0.9, 0.08, 'RT', 'Right'),
      c('rb', 'button', ['shoulderr'], 700, 199, 0.9, 0.2, 'RB', 'Right'),
      c('y', 'button', ['y'], 690, 245, 0.9, 0.32, 'Y', 'Right'),
      c('b', 'button', ['b'], 730, 285, 0.9, 0.43, 'B', 'Right'),
      c('a', 'button', ['a'], 690, 325, 0.9, 0.54, 'A', 'Right'),
      c('x', 'button', ['x'], 650, 285, 0.73, 0.66, 'X', 'Right'),
      c('rs', 'axis', ['thumbrx', 'thumbry'], 600, 372, 0.9, 0.7, 'Right stick', 'Right'),
      c('r3', 'button', ['thumbr'], 620, 392, 0.9, 0.82, 'R3 (press)', 'Right'),
    ],
  },
];
