// Generic built-in device templates (no vendor artwork). The default stick and throttle are original holographic wireframe drawings
// generated by scripts/gen-default-stick.mjs (1000 x 900) and scripts/gen-default-throttle.mjs (1000 x 800); the gamepad is simple
// SVG drawn here (canvas 1000 x 625).
import type { Callout, CalloutKind, DeviceTemplate } from './templates';
import { DEFAULT_STICK_ANCHORS, DEFAULT_STICK_H, DEFAULT_STICK_REGIONS, DEFAULT_STICK_SVG, DEFAULT_STICK_W } from './defaultStickArt';
import { DEFAULT_THROTTLE_ANCHORS, DEFAULT_THROTTLE_H, DEFAULT_THROTTLE_INPUT_REGIONS, DEFAULT_THROTTLE_REGIONS, DEFAULT_THROTTLE_SVG, DEFAULT_THROTTLE_W } from './defaultThrottleArt';

const W = 1000, H = 625;
const svgUrl = (body: string) =>
  `data:image/svg+xml;utf8,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" fill="none" stroke="#7fa6c2" stroke-width="3" stroke-linejoin="round">${body}</svg>`)}`;
const fill = 'fill="#0f2235"';
const btn = (x: number, y: number, r = 11) => `<circle cx="${x}" cy="${y}" r="${r}" ${fill}/>`;

/** callout from pixel coordinates on the 1000 x 625 canvas */
const c = (id: string, kind: CalloutKind, inputs: string[], ax: number, ay: number, bx: number, by: number, label?: string, group?: string): Callout => ({
  id, kind, inputs, anchor: { x: ax / W, y: ay / H }, box: { x: bx, y: by }, ...(label ? { label } : {}), ...(group ? { group } : {}),
});
const hat = (n: number) => ['up', 'right', 'down', 'left'].map((d) => `hat${n}_${d}`);

/* ------------------------------------------------ default stick: anchors and glow regions come from the generated art */
const DW = DEFAULT_STICK_W, DH = DEFAULT_STICK_H;
/** callout on the default stick: `art` names the control in the drawing; box = label centre (fractions) */
const d = (id: string, art: string, kind: CalloutKind, inputs: string[], bx: number, by: number, label?: string, group?: string): Callout => {
  const [ax, ay] = DEFAULT_STICK_ANCHORS[art];
  const region = DEFAULT_STICK_REGIONS[art];
  return { id, kind, inputs, anchor: { x: ax / DW, y: ay / DH }, box: { x: bx, y: by }, ...(label ? { label } : {}), ...(group ? { group } : {}), ...(region ? { region } : {}) };
};
/** callout on the default throttle art (same idea as `d`) */
const TW = DEFAULT_THROTTLE_W, TH = DEFAULT_THROTTLE_H;
const t = (id: string, art: string, kind: CalloutKind, inputs: string[], bx: number, by: number, label?: string, group?: string): Callout => {
  const [ax, ay] = DEFAULT_THROTTLE_ANCHORS[art];
  const region = DEFAULT_THROTTLE_REGIONS[art], inputRegions = DEFAULT_THROTTLE_INPUT_REGIONS[art];
  return { id, kind, inputs, anchor: { x: ax / TW, y: ay / TH }, box: { x: bx, y: by }, ...(label ? { label } : {}), ...(group ? { group } : {}), ...(region ? { region } : {}), ...(inputRegions ? { inputRegions } : {}) };
};
const b = (...n: number[]) => n.map((i) => `button${i}`);
const DEFAULT_THROTTLE: DeviceTemplate = {
  version: 1, id: 'builtin-throttle', name: 'Generic throttle', builtin: true, slot: 'js',
  image: `data:image/svg+xml;utf8,${encodeURIComponent(DEFAULT_THROTTLE_SVG)}`, aspect: TW / TH, match: [],
  callouts: [
    // left column: left grip, left lever, panel (pilot side); ordered so that leader lines do not cross
    t('hat3', 'hat3', 'hat', [...hat(3), 'button10'], 0.125, 0.055, undefined, 'Left grip'),
    t('trgL', 'trgL', 'button', b(4), 0.115, 0.19, 'Left trigger', 'Left grip'),
    t('lz', 'lz', 'axis', ['z'], 0.115, 0.3, 'Left lever', 'Axes'),
    t('sld', 'sld', 'axis', ['slider2'], 0.115, 0.385, 'Slider', 'Axes'),
    t('mode', 'mode', 'switch', b(24, 25, 26, 27, 28), 0.115, 0.48, 'Mode 1 – 5', 'Panel'),
    t('keys', 'keys', 'buttons', b(11, 12, 13, 14, 15, 16), 0.115, 0.585, 'Keypad (lit)', 'Panel'),
    t('e1', 'e1', 'encoder', b(18, 19, 20), 0.115, 0.7, 'Encoder E1', 'Panel'),
    t('red', 'red', 'button', b(17), 0.115, 0.8, 'Emergency (guarded)', 'Panel'),
    // right column: right grip, right lever, flaps
    t('whl', 'whl', 'encoder', b(6, 7), 0.885, 0.055, 'Thumb wheel', 'Right grip'),
    t('hat1', 'hat1', 'hat', [...hat(1), 'button8'], 0.875, 0.165, undefined, 'Right grip'),
    t('ms', 'ms', 'axis', ['x', 'y'], 0.885, 0.3, 'Mini-stick', 'Right grip'),
    t('msb', 'ms', 'button', b(5), 0.885, 0.38, 'Mini-stick press', 'Right grip'),
    t('hat2', 'hat2', 'hat', [...hat(2), 'button9'], 0.875, 0.49, undefined, 'Right grip'),
    t('trgR', 'trgR', 'switch', b(1, 2), 0.885, 0.605, 'Trigger (2-stage)', 'Right grip'),
    t('gb1', 'gb1', 'button', b(3), 0.885, 0.685, 'Thumb button', 'Right grip'),
    t('lrz', 'lrz', 'axis', ['rotz'], 0.885, 0.76, 'Right lever', 'Axes'),
    t('flaps', 'flaps', 'axis', ['slider1'], 0.885, 0.835, 'Flaps lever', 'Axes'),
    t('e2', 'e2', 'encoder', b(21, 22, 23), 0.885, 0.91, 'Encoder E2', 'Panel'),
    // bottom row: toggles T1 – T3
    t('t1', 't1', 'switch', b(29, 30), 0.3, 0.915, 'Toggle T1 (on-off-on)', 'Panel'),
    t('t2', 't2', 'button', b(31), 0.5, 0.915, 'Toggle T2', 'Panel'),
    t('t3', 't3', 'button', b(32), 0.66, 0.915, 'Toggle T3', 'Panel'),
  ],
};

const DEFAULT_STICK: DeviceTemplate = {
  version: 1, id: 'builtin-stick', name: 'Generic stick', builtin: true, slot: 'js',
  image: `data:image/svg+xml;utf8,${encodeURIComponent(DEFAULT_STICK_SVG)}`, aspect: DW / DH, match: [],
  callouts: [
    // left column, top to bottom (grip front / thumb side)
    d('hat1', 'hat1', 'hat', [...hat(1), 'button12'], 0.125, 0.06, undefined, 'Grip head'),
    d('enc', 'enc', 'encoder', ['button10', 'button11'], 0.115, 0.14, 'Thumb wheel', 'Grip head'),
    d('hat3', 'hat3', 'hat', [...hat(3), 'button14'], 0.125, 0.22, undefined, 'Grip head'),
    d('b8', 'b8', 'button', ['button8'], 0.115, 0.3, 'Index button', 'Grip head'),
    d('b6', 'b6', 'button', ['button6'], 0.115, 0.375, 'Thumb button (front)', 'Grip head'),
    d('hat4', 'hat4', 'hat', [...hat(4), 'button15'], 0.125, 0.45, undefined, 'Grip head'),
    d('trig', 'trig', 'switch', ['button1', 'button2'], 0.115, 0.55, 'Trigger (2-stage)', 'Grip'),
    d('b4', 'b4', 'button', ['button4'], 0.115, 0.66, 'Pinky paddle', 'Grip'),
    d('b5', 'b5', 'button', ['button5'], 0.115, 0.75, 'Pinky button', 'Grip'),
    d('rz', 'rz', 'axis', ['rotz'], 0.115, 0.825, 'Twist', 'Axes'),
    d('rowL', 'rowL', 'buttons', ['button16', 'button17', 'button18', 'button19'], 0.125, 0.915, 'Deck buttons (left)', 'Base'),
    // right column, top to bottom (top panel, base deck)
    d('ms', 'ms', 'axis', ['rotx', 'roty'], 0.885, 0.07, 'Mini-stick', 'Grip head'),
    d('msb', 'ms', 'button', ['button9'], 0.885, 0.175, 'Mini-stick press', 'Grip head'),
    d('b3', 'b3', 'button', ['button3'], 0.885, 0.255, 'Weapon release', 'Grip head'),
    d('hat2', 'hat2', 'hat', [...hat(2), 'button13'], 0.875, 0.345, undefined, 'Grip head'),
    d('b7', 'b7', 'button', ['button7'], 0.885, 0.44, 'Thumb button (rear)', 'Grip head'),
    d('rowR', 'rowR', 'buttons', ['button20', 'button21', 'button22', 'button23'], 0.875, 0.53, 'Deck buttons (right)', 'Base'),
    d('tog2', 'tog2', 'switch', ['button26', 'button27'], 0.885, 0.615, 'Toggle (right)', 'Base'),
    d('xy', 'xy', 'axis', ['x', 'y'], 0.885, 0.715, 'Stick X / Y', 'Axes'),
    d('fkeys', 'fkeys', 'buttons', ['button28', 'button29', 'button30'], 0.875, 0.825, 'F1 – F3', 'Base'),
    d('tog1', 'tog1', 'switch', ['button24', 'button25'], 0.885, 0.915, 'Toggle (left)', 'Base'),
    // bottom row: the three thumbwheels on the sloped pilot panel
    d('whl1', 'whl1', 'axis', ['slider1'], 0.33, 0.955, 'Lever wheel', 'Base'),
    d('whl2', 'whl2', 'axis', ['slider2'], 0.5, 0.955, 'Centre wheel', 'Base'),
    d('whl3', 'whl3', 'encoder', ['button31', 'button32'], 0.67, 0.955, 'Encoder EN1', 'Base'),
  ],
};

const GAMEPAD = svgUrl([
  '<path d="M300 205 Q500 170 700 205 Q790 220 815 330 Q840 470 770 500 Q720 515 680 450 L640 410 L360 410 L320 450 Q280 515 230 500 Q160 470 185 330 Q210 220 300 205 Z" fill="#0b1a2a"/>',
  '<rect x="262" y="150" width="76" height="28" rx="12" fill="#0f2235"/><rect x="662" y="150" width="76" height="28" rx="12" fill="#0f2235"/>',
  '<rect x="258" y="190" width="84" height="18" rx="8" fill="#0f2235"/><rect x="658" y="190" width="84" height="18" rx="8" fill="#0f2235"/>',
  '<circle cx="310" cy="285" r="34" fill="#0f2235"/><circle cx="310" cy="285" r="20"/>',
  '<circle cx="610" cy="380" r="34" fill="#0f2235"/><circle cx="610" cy="380" r="20"/>',
  '<path d="M378 352 h24 v24 h24 v24 h-24 v24 h-24 v-24 h-24 v-24 h24 z" fill="#0f2235"/>',
  btn(690, 245, 15), btn(730, 285, 15), btn(690, 325, 15), btn(650, 285, 15),
  '<rect x="440" y="275" width="30" height="16" rx="8" fill="#0f2235"/><rect x="530" y="275" width="30" height="16" rx="8" fill="#0f2235"/>',
].join(''));

export const BUILTIN_TEMPLATES: DeviceTemplate[] = [
  DEFAULT_STICK,
  DEFAULT_THROTTLE,
  {
    version: 1, id: 'builtin-gamepad', name: 'Gamepad', builtin: true, slot: 'gp', image: GAMEPAD, aspect: W / H, match: [],
    callouts: [
      c('lt', 'button', ['triggerl_btn'], 300, 162, 0.1, 0.08, 'LT', 'Left'),
      c('lb', 'button', ['shoulderl'], 300, 199, 0.1, 0.2, 'LB', 'Left'),
      c('ls', 'axis', ['thumblx', 'thumbly'], 300, 280, 0.1, 0.33, 'Left stick', 'Left'),
      c('l3', 'button', ['thumbl'], 318, 292, 0.1, 0.46, 'L3 (press)', 'Left'),
      c('dpad', 'hat', ['dpad_up', 'dpad_right', 'dpad_down', 'dpad_left'], 390, 388, 0.1, 0.63, 'D-pad', 'Left'),
      c('back', 'button', ['back'], 455, 283, 0.32, 0.92, 'Back / View'),
      c('start', 'button', ['start'], 545, 283, 0.66, 0.92, 'Start / Menu'),
      c('rt', 'button', ['triggerr_btn'], 700, 162, 0.9, 0.08, 'RT', 'Right'),
      c('rb', 'button', ['shoulderr'], 700, 199, 0.9, 0.2, 'RB', 'Right'),
      c('y', 'button', ['y'], 690, 245, 0.9, 0.32, 'Y', 'Right'),
      c('b', 'button', ['b'], 730, 285, 0.9, 0.43, 'B', 'Right'),
      c('a', 'button', ['a'], 690, 325, 0.9, 0.54, 'A', 'Right'),
      c('x', 'button', ['x'], 650, 285, 0.73, 0.66, 'X', 'Right'),
      c('rs', 'axis', ['thumbrx', 'thumbry'], 600, 372, 0.9, 0.7, 'Right stick', 'Right'),
      c('r3', 'button', ['thumbr'], 620, 392, 0.9, 0.82, 'R3 (press)', 'Right'),
    ],
  },
];
